[[language]]
name = "chimera"
scope = "source.chimera"
injection-regex = "chimera"
file-types = ["chi"]
language-servers = ["mychimeralsp"]
comment-token = ";"
indent = { tab-width = 3, unit = "   " }

[[grammar]]
name = "chimera"
source = { git = "https://github.com/l1onsun/tree-sitter-chimera", rev = "fca66ee0ea76ae697706761129362f806b7ce22d" }

[language-server.mychimeralsp]
command = "python"
args = ["lsp"]

# [[grammar]]
# name = "walktime"
# source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "1f63b33efee17e833e0ea29266dd3d713e27e321" }
# formatter.command = "sh"
# formatter.args = [
#   "-c",
#   "black --quiet - | isort --profile black -",
# ]


